services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # port for qbittorrent
      - 9696:9696 # port for prowlarr
      - 9118:9117 # port for jackett2
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - PUID=1026
      - PGID=101
      - VPN_SERVICE_PROVIDER="private internet access"
      - VPN_TYPE=openvpn
      - OPENVPN_USER=<pia_username>
      - OPENVPN_PASSWORD=<pia_password>
      - SERVER_REGIONS="UK London"
      - TZ=Europe/London
      - HTTPPROXY=off #change to on if you wish to enable
      - SHADOWSOCKS=off #change to on if you wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.19.0.0/16,192.168.1.0/24 #change this in line with your subnet see note on guide.
#     - FIREWALL_VPN_INPUT_PORTS=12345 #uncomment this line and change the port as per the note on the guide. inbound port fwd
    network_mode: synobridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
      - WEBUI_PORT=8090
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume2/volume2/downloads:/downloads
      - /volume2/volume2/tv-sonarr-daily:/tv-sonarr-daily
      - /volume2/volume2/tv-sonarr:/data/tv-sonarr
      - /volume2/volume2/movies-radarr:/data/movies-radarr
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    tty: true
    restart: unless-stopped

  linuxserver-jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/docker/jackett2/config:/config
      - /volume2/volume2/downloads:/downloads
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
